title: Recipe
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              display: Title
              validate:
                - required
          -
            import: content
            prefix: intro_
          -
            handle: ingredients_sections
            field:
              collapse: accordion
              type: replicator
              display: 'Ingredients Sections'
              sets:
                new_set_group:
                  display: 'New Set Group'
                  sets:
                    new_ingredients_section:
                      display: 'New Ingredients Section'
                      fields:
                        -
                          handle: name
                          field:
                            type: text
                            display: Name
                            instructions: 'e.g. Sauce ingredients'
                        -
                          handle: items
                          field:
                            type: list
                            display: Items
          -
            handle: method
            field:
              collapse: true
              type: replicator
              display: Method
              sets:
                new_set_group:
                  display: 'New Set Group'
                  sets:
                    step:
                      display: Step
                      fields:
                        -
                          handle: name
                          field:
                            type: text
                            display: Name
                            instructions: 'e.g. Preparation'
                        -
                          handle: steps
                          field:
                            type: replicator
                            display: Steps
                            sets:
                              new_set_group:
                                display: 'New Set Group'
                                sets:
                                  step:
                                    display: Step
                                    fields:
                                      -
                                        handle: step_content
                                        field:
                                          buttons:
                                            - bold
                                            - italic
                                            - anchor
                                            - underline
                                          remove_empty_nodes: false
                                          type: bard
                                          display: 'Step Content'
                                          inline: break
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: excerpt
            field:
              type: textarea
              display: Excerpt
              character_limit: 160
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
          -
            handle: date
            field:
              type: date
              required: true
              default: now
              validate:
                - required
          -
            handle: author
            field:
              max_items: 1
              collections:
                - authors
              type: entries
              display: Author
          -
            handle: topics
            field:
              type: terms
              taxonomies:
                - topics
              display: Topics
              mode: select
          -
            handle: source
            field:
              type: link
              display: Source
              instructions: 'Reference the original recipe if not original / passed down'
          -
            handle: featured_image
            field:
              max_files: 1
              container: assets
              folder: content
              dynamic: slug
              type: assets
              display: 'Featured Image'
          -
            handle: servings
            field:
              type: text
              display: Servings
